---
platform: linux

inputs:
  - name: repo

caches:
- path: repo/node_modules

image_resource:
  type: docker-image
  source:
    repository: mhart/alpine-node

run:
  path: sh
  args:
    - -exc
    - |
      source repo/ci/scripts/bootstrap.sh
      dependencies mongodb
      mkdir -p /data/db
      /usr/bin/mongod --quiet --syslog --noauth --fork
      npm run test:ci
      nyc report --reporter=text-lcov | coveralls

params:
  NODE_ENV: development
  CI: true
  COVERALLS_SERVICE_NAME: DecentM's Concourse
  COVERALLS_REPO_TOKEN: ((coverallsToken))
